### ISSUE TITLE
Using mirror.vim to save both locally and in staging at the same time.

### ISSUE THREAD

**Issue by partounian** [zenbro/mirror.vim#10]
So my plan is to essentially live edit my local and staging branch at the same time. At this time, I will also be keeping a gulpfile with browser to load my site when changes are made and in this way I can live the staging site locally. 

Therefore, my question is, how can I use mirror.vim to save both locally and in staging?

**Comment by zenbro** [comment]
Hi!
Here is example binding for your task:

``` vim
nnoremap <F5> :write<CR>:MirrorPush staging<CR>
```

It saves file via `:w` then push it to the staging.

Hope it helps.

**Comment by partounian** [comment]
Thank you zenbro! 
I have never really written custom vim before, just mostly copy-pasting with small modifications and never thought of this. I appreciate the answer.
