### ISSUE TITLE
Jump to directory when using :MirrorSSH

### ISSUE THREAD

**Issue by willdurney** [zenbro/mirror.vim#2]
Great plugin! Would it be possible to have `:MirrorSSH` automatically jump to the directory as specified in the config?

For example, if config looks like this:

``` yml
/home/user/work/project2:
  staging: project2@another_host:23//opt/project2
```

`:MirrorSSH` could do something like this:

``` sh
ssh -p 23 -t project2@another_host "cd /opt/project2 && $SHELL"
```

**Comment by zenbro** [comment]
Good idea. Thank you!

Auto jump will be enabled by default for `MirrorSSH`. See also `g:mirror#ssh_auto_cd` and `g:mirror#ssh_shell` in readme and documentation.
