### ISSUE TITLE
Automatically read git-config?

### ISSUE THREAD

**Issue by Anachron** [zenbro/mirror.vim#3]
Hey there,

nice Plugin you got here!
I've been wondering: Is it possible to read the remote targets from the git-directory?
So this way we wouldn't have to configure it twice.

Kind regards.

**Comment by zenbro** [comment]
Hi!
Did you mean `.git/config` file and `url` (e.g. `git@github.com:user/project.git` for ssh and `https://github.com/user/project.git` for https) from this config?
I can't imagine any possible use case for this feature. Can you explain exactly how it should work (using remote targets from git config to set remote location of project for different environment)?

**Comment by Anachron** [comment]
I was thinking about being able to change files between different origins or even branches. (Like not needing stash/checkout all the time to compare files)
This way I could quickly compare which branch has which state.

Was that clear enough?

**Comment by zenbro** [comment]
Yes, that was clear enough, but this plugin have different purpose and have nothing to do with git origins and branches.
Take a look at VimCasts about [fugitive](https://github.com/tpope/vim-fugitive) ([#31](http://vimcasts.org/episodes/fugitive-vim---a-complement-to-command-line-git/), [#32](http://vimcasts.org/episodes/fugitive-vim-working-with-the-git-index/), [#33](http://vimcasts.org/episodes/fugitive-vim-resolving-merge-conflicts-with-vimdiff/), [#34](http://vimcasts.org/episodes/fugitive-vim-browsing-the-git-object-database/), [#35](http://vimcasts.org/episodes/fugitive-vim-exploring-the-history-of-a-git-repository/)) and [vim-merginal](https://github.com/idanarye/vim-merginal).
