### ISSUE TITLE
Does mirror.vim support a remote development environment (with qa, staging, production also remote)?

### ISSUE THREAD

**Issue by jfoo1984** [zenbro/mirror.vim#4]
@zenbro If my development environment is also on a remote server, does this plugin also support that?

**Comment by zenbro** [comment]
No, it doesn't. You need a local copy of your project that should be used as entry point to any remote environment.

**Comment by jfoo1984** [comment]
would it be difficult to support a remote development environment as well?  I haven't taken a look into it, but I'd be willing to.

**Comment by zenbro** [comment]
How you will use it? Could you provide some steps to reproduce this use case.

**Comment by jfoo1984** [comment]
For my job, I currently do my dev work on a remote server (and then there are other remote servers for QA, staging, etc.).  I currently have an IDE with remote server access set up, but I'm exploring switching to VIM, and this seemed like it might be a viable alternative.

**Comment by zenbro** [comment]
You already can use mirror.vim for this use case but it can be a little bit tricky.

First, set up passwordless authenitcation via ssh-key to each of your remote servers.
Then enable ssh-agent forwarding for all your remote servers by adding this to your `~/.ssh/config`:

```
Host * 
ForwardAgent yes
```

Now you can jump from server to server without input any login/password.

Then set up vim on development server and add others server to `.mirrors` config. By being on your development server (connected via ssh), you should be able to edit any files on others server via mirror.vim.

That's how its looks like and there is no an easy way, sorry. :pensive: Maybe using special IDE is better for this use case.

**Comment by zenbro** [comment]
Also you can mount any directory from remote server via [sshfs](https://wiki.archlinux.org/index.php/SSHFS).

**Comment by zenbro** [comment]
Added information about sshfs to docs and readme (0d37c4bbbc7d283ac59483835d87efa1235566d6). It should helps with this kind of problems.
