### ISSUE TITLE
Add :MirrorConfigReload command

### ISSUE THREAD

**Issue by jakubgs** [zenbro/mirror.vim#7]
Hello! It's me again to bother you.

I've written myself a small function that runs when I open project files that checks whether the project is already in the `mirrors.yml` file with `readfile()` and `match()` and if not it appends a rudimentary config for that particular project using `writefile()`.

The issue is, your plugin does not recognize the fact that a new project has been added to my `mirrors.yml` and i have to restart vim in order for this to take effect.

Don't know how hard adding a `:MirrorConfigReload` command would be to implement but I think it's an essential feature.

YO!

**Comment by zenbro** [comment]
Done! :smiley:

**Comment by jakubgs** [comment]
Holy shit man! THANKS a bunch!

I see the change wasn't that hard. That just shows that your design is good :D.
