### ISSUE TITLE
Add a "wildcard" like syntax to mirrors config

### ISSUE THREAD

**Issue by jakubgs** [zenbro/mirror.vim#8]
This is and idea I had in relation to the issue I just opened: https://github.com/zenbro/mirror.vim/issues/7

I was wondering if mirror.vim config could have a wildcard-like syntax which would match all projects in a directory. For example:

``` yml
/home/user/projects/*:
    devel: username@some_host.local//some/workplace/*/src/*
```

Which effectively works for any project in that directory, for example `/home/user/projects/ProjectA` and works **as if** this existed in the config:

``` yml
/home/user/projects/ProjectA:
    devel: username@some_host.loca//some/workplace/ProjectA/src/ProjectA
```

That would be pretty cool but I expect it to be hard to implement so this is probably a pretty big feature request.

**Comment by zenbro** [comment]
Thank you for cool idea!
I will try.

**Comment by zenbro** [comment]
Done!
Thank you again for inspiring ideas. :thumbsup:

**Comment by jakubgs** [comment]
That's amazing. I'll have to go through the commit later when I'm not drunk to learn a bit of vimscript.
